improved python version detection on python binding installation

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -110,6 +110,7 @@ find_hdf5(){
 
 try_find_boost(){
 	GUESS_DIR=$1
+  PYTHONVERSION=$2
 	PKG=boost
 	VAR_PREFIX=`echo $PKG | tr [:lower:] [:upper:]`
 	TMP_FOUND=`eval echo "$"${VAR_PREFIX}_FOUND`
@@ -118,12 +119,12 @@ try_find_boost(){
 	POSSIBLE_BOOST_LIBDIRS="${GUESS_DIR}/lib ${GUESS_DIR}/lib64 ${GUESS_DIR}/lib/x86_64-linux-gnu"
 	POSSIBLE_BOOST_INCDIRS="${GUESS_DIR}/include"
 	for BOOST_LIBDIR in $POSSIBLE_BOOST_LIBDIRS; do
-		if [ -d $BOOST_LIBDIR -a \( -e $BOOST_LIBDIR/libboost_python.a -o -e $BOOST_LIBDIR/libboost_python.so \) ]; then
+		if [ -d $BOOST_LIBDIR -a \( -e $BOOST_LIBDIR/libboost_python$PYTHONVERSION.a -o -e $BOOST_LIBDIR/libboost_python$PYTHONVERSION.so \) ]; then
 			break
 		fi
 	done
-	if [ ! -d $BOOST_LIBDIR -o ! \( -e $BOOST_LIBDIR/libboost_python.a -o -e $BOOST_LIBDIR/libboost_python.so \) ]; then
-		echo " Unable to locate the boost_python libray in $GUESS_DIR"
+	if [ ! -d $BOOST_LIBDIR -o ! \( -e $BOOST_LIBDIR/libboost_python$PYTHONVERSION.a -o -e $BOOST_LIBDIR/libboost_python$PYTHONVERSION.so \) ]; then
+		echo " Unable to locate the boost_python$PYTHONVERSION libray in $GUESS_DIR"
 		return
 	fi
 	for BOOST_INCDIR in $POSSIBLE_BOOST_INCDIRS; do
@@ -136,7 +137,7 @@ try_find_boost(){
 		return
 	fi
 	BOOST_CFLAGS="-I${BOOST_INCDIR}"
-	BOOST_LDFLAGS="-Wl,-rpath -Wl,${BOOST_LIBDIR} -L${BOOST_LIBDIR} -lboost_python"
+	BOOST_LDFLAGS="-Wl,-rpath -Wl,${BOOST_LIBDIR} -L${BOOST_LIBDIR} -lboost_python$PYTHONVERSION"
 	BOOST_FOUND=1
 	echo " Found boost in $GUESS_DIR"
 }
@@ -621,22 +622,36 @@ echo "../lib:${SQUIDS_LIBDIR}:${GSL_LIBDIR}:${HDF5_LIBDIR}\"" >> test/env_vars.s
 if [ $PYTHON_BINDINGS ]; then
 	echo "Generating Python bindings makefile..."
 
+	PYTHONVERSION=`${PYTHON_EXE} -c 'import sys; print(str(sys.version_info.major)+"."+str(sys.version_info.minor))'`
+	PYTHONVERSIONSIMPLE=`${PYTHON_EXE} -c 'import sys; print(str(sys.version_info.major)+"."+str(sys.version_info.minor))'`
+	PYTHONLIBPATH=`${PYTHON_EXE} -c 'import sys; import re; print([ y for y in sys.path if re.search("\/lib\/python'$PYTHONVERSION'$",y)!=None ][0]);'`
+	PYTHONINCPATHS=`find $PYTHONLIBPATH/../../include/ -name "python${PYTHONVERSION}*"`
+  for proposed_path in $PYTHONINCPATHS; do
+    PYTHON_CFLAGS="$PYTHON_CFLAGS -I$proposed_path"
+  done
+	PYTHONNUMPYCHECK=`${PYTHON_EXE} ./resources/check_numpy.py`
+	if [ -z "$PYTHONNUMPYCHECK" ]; then
+		echo "Error: numpy not found. Specify numpy installation location with --with-numpy-incdir."
+		exit 1
+	fi
+	PYTHONNUMPYINC=$PYTHONNUMPYCHECK
+
 	if [ "$BOOST_INCDIR" -a "$BOOST_LIBDIR" ]; then
 		echo "Checking manually specified boost..."
 		if [ -d "$BOOST_INCDIR" \
 		  -a -d "$BOOST_LIBDIR" \
 		  -a -e "$BOOST_INCDIR/boost/python.hpp" \
-		  -a -e "$BOOST_LIBDIR/libboost_python.a" ]; then
+		  -a -e "$BOOST_LIBDIR/libboost_python${PYTHONVERSIONSIMPLE//.}.a" ]; then
 			BOOST_FOUND=1
 			BOOST_CFLAGS="-I$BOOST_INCDIR"
-			BOOST_LDFLAGS="-Wl,-rpath -Wl,${BOOST_LIBDIR} -L$BOOST_LIBDIR -lboost_python"
+			BOOST_LDFLAGS="-Wl,-rpath -Wl,${BOOST_LIBDIR} -L$BOOST_LIBDIR -lboost_python${PYTHONVERSIONSIMPLE//.}"
 		else
 			echo "Warning: manually specifed boost not found; will attempt auto detection"
 		fi
 	fi
 
-	try_find_boost /usr
-	try_find_boost /usr/local
+	try_find_boost /usr ${PYTHONVERSIONSIMPLE//.}
+	try_find_boost /usr/local ${PYTHONVERSIONSIMPLE//.}
 
 	if [ -z $BOOST_LIBDIR -a  -z $BOOST_INCDIR ]; then
 		echo "Error: Specify BOOST library path using --with-boost-libdir and BOOST include path using --with-boost-incdir."
@@ -651,18 +666,6 @@ if [ $PYTHON_BINDINGS ]; then
 		exit 1
 	fi
 
-	PYTHONVERSION=`${PYTHON_EXE} -c 'import sys; print(str(sys.version_info.major)+"."+str(sys.version_info.minor))'`
-	PYTHONLIBPATH=`${PYTHON_EXE} -c 'import sys; import re; print([ y for y in sys.path if re.search("\/lib\/python'$PYTHONVERSION'$",y)!=None ][0]);'`
-	PYTHONINCPATHS=`find $PYTHONLIBPATH/../../include/ -name "python${PYTHONVERSION}*"`
-  for proposed_path in $PYTHONINCPATHS; do
-    PYTHON_CFLAGS="$PYTHON_CFLAGS -I$proposed_path"
-  done
-	PYTHONNUMPYCHECK=`${PYTHON_EXE} ./resources/check_numpy.py`
-	if [ -z "$PYTHONNUMPYCHECK" ]; then
-		echo "Error: numpy not found. Specify numpy installation location with --with-numpy-incdir."
-		exit 1
-	fi
-	PYTHONNUMPYINC=$PYTHONNUMPYCHECK
 	echo "
 # Compiler
 CC=$CC
